name: pg-dump
description: Run pg_dump to generate a backup
author: tj-actions
inputs:
  database_url:
    description: 'Database URL'
    required: true
  path:
    description: 'Backup file output location'
    required: true
  options:
    description: 'Extra arguments passed to pg_dump'
    required: true
    default: '-O'

runs:
  using: 'composite'
  steps:
    - run: |
        mkdir -p $(dirname "${{ inputs.path }}")
        pg_dump ${{ inputs.options }} -d "${{ inputs.database_url }}" > "${{ inputs.path }}"
      shell: bash
branding:
  icon: hard-drive
  color: white
